### ISSUE TITLE
Django running with debug=true

### ISSUE THREAD

**Issue by tswfi** [TampereHacklab/mezzanine#2]
https://tampere.hacklab.fi/asdf/

shows that the site is running with debug = true

**Comment by tswfi** [comment]
local_settings.py contains DEBUG=True

too tired to change it right now.

**Comment by tswfi** [comment]
it looks like the apache proxy is not configured to serve the static files, django wont serve them either if debug=false..

**Comment by vranki** [comment]
Yep, this change must be done in apache-proxy config. I don't remember if mezzanine container exposes the static directory - that must also be done if it's not found.

**Comment by tswfi** [comment]
This was fixed

https://matrix.to/#/!jyWBEJPyRHmMunoagX:irc.snt.utwente.nl/$1558796263391520SfoWd:matrix.org?via=irc.snt.utwente.nl&via=hacklab.fi&via=matrix.org

:+1:
