### ISSUE TITLE
Deprecated MW's

### ISSUE THREAD

**Issue by vranki** [TampereHacklab/mezzanine#5]
Starting server says:

/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py:58: FutureWarning: `TemplateForDeviceMiddleware` is deprecated. Please remove it from your middleware settings.
  mw_instance = mw_class()
/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py:58: FutureWarning: `TemplateForHostMiddleware` is deprecated. Please upgrade to the template loader. See: https://goo.gl/SzHPR4
  mw_instance = mw_class()

**Comment by tswfi** [comment]
#8 should fix this

**Comment by tswfi** [comment]
and it did
